### ISSUE TITLE
大佬，怎么移植的？用的wepoll?

### ISSUE THREAD

**Issue by miaomiao1992** [tomwillow/MyMuduo-Win#1]

**Comment by tomwillow** [comment]
你好，我是用muduo源码改的，把socket API改到适配windows，然后把poll/epoll部分改成select。

select性能不如epoll的，windows上的高效IO模型是IOCP，但IOCP是proactor模型，和muduo适配不了。

没有用wepoll。

另外这个项目我不记得有没有写完了。
